### PR TITLE
draft of mice vignette

### PR DESCRIPTION
**Pull request by TysonStanley**
Had a meeting cancel so I wanted to get a draft up before other things came up. Feel free to adjust all you want but the approach is looking good from the limited examples I show in the vignette.

### CODE REVIEW

**Comment by TysonStanley** [comment]
Closes #345

**Comment by vincentarelbundock** [comment]
Thanks, this looks fantastic!

I added a couple calls to `modelsummary()` to compare the missing, complete, and imputed models side by side. 

Can't wait to see what it looks like live!

**Comment by TysonStanley** [comment]
Oh, brilliant! I'm sure there were random things I missed because I went pretty quick but was excited there was a relatively straightforward way of handling this.

**Comment by vincentarelbundock** [comment]
Yep, looks quite nice: https://vincentarelbundock.github.io/marginaleffects/articles/multiple_imputation.html

Thanks again!

**Pull request merged**
