### PR TITLE
Improve speed of `predictions()`

### PR DESCRIPTION
**Pull request by etiennebacher**
Benchmark:
``` r
library(marginaleffects)

tmp <- list()
for (i in 1:30000) {
  tmp[[i]] <- mtcars
}
tmp2 <- data.table::rbindlist(tmp)
tmp2$am <- as.logical(tmp2$am)
dim(tmp2)
#> [1] 960000     11

mod <- lm(mpg ~ hp + factor(cyl), data = tmp2)
```
Old:
```r
bench::mark(
  predictions(mod, variables = list(hp = c(100, 120))),
  predictions(mod, newdata = datagridcf(hp = c(100, 120), cyl = c(4, 6))),
  check = FALSE
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 2 × 6
#>   expression                                                                 min
#>   <bch:expr>                                                              <bch:>
#> 1 predictions(mod, variables = list(hp = c(100, 120)))                     12.4s
#> 2 predictions(mod, newdata = datagridcf(hp = c(100, 120), cyl = c(4, 6)))  21.2s
#> # … with 4 more variables: median <bch:tm>, `itr/sec` <dbl>,
#> #   mem_alloc <bch:byt>, `gc/sec` <dbl>
```
New:
``` r
bench::mark(
  predictions(mod, variables = list(hp = c(100, 120))),
  predictions(mod, newdata = datagridcf(hp = c(100, 120), cyl = c(4, 6))),
  check = FALSE
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 2 × 6
#>   expression                                                                 min
#>   <bch:expr>                                                              <bch:>
#> 1 predictions(mod, variables = list(hp = c(100, 120)))                     9.08s
#> 2 predictions(mod, newdata = datagridcf(hp = c(100, 120), cyl = c(4, 6)))  8.23s
#> # … with 4 more variables: median <bch:tm>, `itr/sec` <dbl>,
#> #   mem_alloc <bch:byt>, `gc/sec` <dbl>
```

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Very cool!

Have you tried the `cjdt()` function here? https://github.com/vincentarelbundock/marginaleffects/blob/main/R/utils.R#L62

**Comment by etiennebacher** [comment]
It's a 3-4 seconds slower for me (but I did only 1 iteration so could be just because of noise). Depends if you prefer saving these seconds or make the code more readable

**Comment by etiennebacher** [comment]
Do you know why the tests are cancelled? One failed because it couldn't download Ubuntu, did it trigger the cancellation for the rest?

**Comment by vincentarelbundock** [comment]
> It's 3-4 seconds slower for me (but I did only 1 iteration so could be just because of noise). Depends if you prefer saving these seconds or make the code more readable

Cool thanks. Let's keep the faster version, as long as it passes tests. Maybe just include a comment to say that this is faster than the equivalent `cjdt`.

> Do you know why the tests are cancelled? One failed because it couldn't download Ubuntu, did it trigger the cancellation for the rest?

Yes, that's my guess. I've noticed that Github seems to have changed their policy (or something in my repo settings). When one machine of a single "matrix" fails, the others are cancelled.

**Comment by etiennebacher** [comment]
Using `cjdt()`:
``` r
bench::mark(
  predictions(mod, variables = list(hp = c(100, 120))),
  predictions(mod, newdata = datagridcf(hp = c(100, 120), cyl = c(4, 6))),
  check = FALSE,
  iterations = 10
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 2 × 6
#>   expression                                                                 min
#>   <bch:expr>                                                              <bch:>
#> 1 predictions(mod, variables = list(hp = c(100, 120)))                     5.97s
#> 2 predictions(mod, newdata = datagridcf(hp = c(100, 120), cyl = c(4, 6)))  6.64s
#> # … with 4 more variables: median <bch:tm>, `itr/sec` <dbl>,
#> #   mem_alloc <bch:byt>, `gc/sec` <dbl>
```
Cool trick!

**Comment by vincentarelbundock** [comment]
Wait, so `cjdt()` is faster after all ?!

**Comment by etiennebacher** [comment]
> Wait, so `cjdt()` is faster after all ?!

I think so, I'm re-running the first benchmark with several iterations to confirm

**Comment by etiennebacher** [comment]
Timings are very close (a few milliseconds) so let's keep `cjdt()` that is easier to read

**Comment by vincentarelbundock** [comment]
Cool, thanks. Let me know when you want me to merge.

**Comment by vincentarelbundock** [comment]
thanks for another great improvement.

**Pull request merged**
