### PR TITLE
`data.frame` support for hypotheses testing

### PR DESCRIPTION
**Pull request by kylebutts**
For #838:

- Implements `get_coef` and `set_coef` for data.frame that basically grabs and changes the estimate column.
- For `FUN_inner` in hypotheses, implements a method for data.frame that checks column names and extracts the `coeftable`. This is to remove the need to provide `FUN = function(x) x` as an argument. It comes after the check for `c("predictions", "slopes", "comparisons")`, so it doesn't mess up those methods.
- Adds a small section to the book with an example. Feel free to remove that or put it anywhere else!

Here's an example:

``` r
library(marginaleffects)

mod <- lm(mpg ~ am + vs, data = mtcars)
coeftable <- data.frame(term = names(mod$coefficients), estimate = as.numeric(mod$coefficients))
vcov <- vcov(mod)

hypotheses(
  coeftable, vcov = vcov, 
  hypothesis = "am = vs"
)
#> 
#>     Term Estimate Std. Error      z Pr(>|z|)   S 2.5 % 97.5 %
#>  am = vs   -0.863       1.94 -0.445    0.656 0.6 -4.66   2.94
#> 
#> Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
```

<sup>Created on 2023-07-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Thanks so much, this is awesome!

Can you think of a simple (compelling) example I could add to the documentation? It can be silly/ridiculous, but just something to highlight the generality and something that can’t be done more straightforwardly like:

``` r
library(marginaleffects)
mod <- lm(mpg ~ am + vs, data = mtcars)
hypotheses(mod, "am = vs")
# 
#     Term Estimate Std. Error      z Pr(>|z|)   S 2.5 % 97.5 %
#  am = vs   -0.863       1.94 -0.445    0.656 0.6 -4.66   2.94
# 
# Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
```

**Comment by kylebutts** [comment]
How bout this? Run a monte-carlo simulation and you want to perform hypothesis of various quantities returned from each simulation. The quantities are correlated within each draw.

``` r
draw <- function(i) { 
  x <- rnorm(n = 10000, mean = 0, sd = 1)
  data.frame(median = median(x), mean =  mean(x))
}

sims = purrr::map_dfr(1:25, draw)

coeftable = data.frame(
  term = c("median", "mean"),
  estimate = c(mean(sims$median), mean(sims$mean))
)
vcov = cov(sims)

marginaleffects::hypotheses(
  coeftable, vcov = vcov,
  hypothesis = "median = mean"
)
#> 
#>           Term Estimate Std. Error      z Pr(>|z|)   S   2.5 % 97.5 %
#>  median = mean -0.00126    0.00869 -0.145    0.885 0.2 -0.0183 0.0158
#> 
#> Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
```

<sup>Created on 2023-07-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
This is per-fect! Live on the dev site now, will try to release to CRAN tonight.

Screenshot 2023-07-24 201132

**Comment by vincentarelbundock** [comment]
turns out cran is on vacation, so the release will have to wait a few weeks.

**Pull request merged**
