### PR TITLE
Add `facet_grid` support with 4 conditions

### PR DESCRIPTION
**Pull request by Tristan-Siegfried**
Add support for 4 conditions and facet_grid, resolving #939 

A nuance here: When labelling facets, if doing `facet_grid` I use `label_both` in order to disambiguate the facet rows/columns, but in the case of `multi_variables` we also want to remove `marginaleffects` internal variable renaming, so do string processing as well.

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Thanks, I'm very excited about this. I'm off the computer now for the weekend, but will look at this next week for sure.

**Comment by vincentarelbundock** [comment]
I had a few minutes this morning and took a look. Overall this looks great!

I updated to `main` and fixed a namespace issue.

There's at least one failing test and I can't really figure out the cause. I think it's this one: https://github.com/vincentarelbundock/marginaleffects/blob/main/inst/tinytest/test-plot_predictions.R#L187

If you want, you can also add your info to `DESCRIPTION` as a `ctb`. (Optional)

**Comment by nhimwich** [comment]
Thanks for this.
Indeed there was a bug, so I'm sorry for that. 
I believe it is now testing all the plotting tests.

**Comment by vincentarelbundock** [comment]
Thanks a lot!

Merged into main now and will be part of the next release.

This is a very nice change.

**Pull request merged**
