### PR TITLE
fixed() not found after #1064

### LINKED ISSUE #1084: `fixed()` not found after #1064
Sorry for the long reprex, I just copied it from the failing test in _ggeffects_:

``` r
library(marginaleffects)
data(efc, package = "ggeffects")
efc <- datawizard::to_factor(efc, select = c("c161sex", "c172code", "c175empl"))
efc <- datawizard::recode_values(
  efc,
  select = "c160age",
  recode = list(`1` = "min:40", `2` = 41:64, `3` = "65:max")
)
efc <- datawizard::data_rename(
  efc,
  pattern = c("c161sex", "c160age", "quol_5", "c175empl"),
  replacement = c("gender", "age", "qol", "employed")
)
efc <- datawizard::data_modify(efc, age = factor(age, labels = c("-40", "41-64", "65+")))
m_null <- glmmTMB::glmmTMB(qol ~ 1 + (1 | gender:employed:age), data = efc)

datagrid <- ggeffects::data_grid(m_null, c("gender", "employed", "age"))
avg_predictions(m_null, variables = c("gender", "employed", "age"))
#> Warning: For this model type, `marginaleffects` only takes into account the
#>   uncertainty in fixed-effect parameters. You can use the `re.form=NA`
#>   argument to acknowledge this explicitly and silence this warning.
#> Error in fixef(model): could not find function "fixef"
```

<sup>Created on 2024-04-13 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by strengejacke**
Fixes #1084

### CODE REVIEW

**Comment by strengejacke** [comment]
``` r
library(marginaleffects)
m_null <- glmmTMB::glmmTMB(Sepal.Length ~ 1 + (1 | Species), data = iris)
avg_predictions(m_null, variables = "Species")
#> Warning: For this model type, `marginaleffects` only takes into account the
#>   uncertainty in fixed-effect parameters. You can use the `re.form=NA`
#>   argument to acknowledge this explicitly and silence this warning.
#> Error in fixef(model): could not find function "fixef"
```

<sup>Created on 2024-04-13 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Not sure how you deal with namespace, I just added `insight::check_if_installed("lme4")`.

**Comment by vincentarelbundock** [comment]
Thanks! But shouldn't we call glmmTMB::fixef.glmmTMB instead of loading a different package?

**Comment by vincentarelbundock** [comment]
thanks, merged using the `glmmTMB` namespace export

**Comment by strengejacke** [comment]
> Thanks! But shouldn't we call glmmTMB::fixef.glmmTMB instead of loading a different package?

glmmTMB imports lme4 anyway, because of the generic located there, I guess. But that's up to you what you prefer in your codebase :-)

**Comment by strengejacke** [comment]
I cloned the repo locally, and tried to add a test, but couldn't install the package via the MAKE file. Always gave an error, saying something like "could not remove prior installation, is it in use?" (but it wasn't)

**Pull request merged**
