### PR TITLE
Extend support to gamlss objects

### PR DESCRIPTION
**Pull request by dnzmarcio**
The function `predict` of the R-package `gamlss` refits every model using weighted least squares with the original data independently whether a new dataset is provided to achieve "safe" predictions. In case predictions from the refitted model differs from the original model, the function `predict` replaces the coefficients in the original model by the refitted model. Consequently, the function `set_coef` does not modify the result of the function predict and we cannot calculate standard errors using the method Delta numerically. See example below.

```
library(gamlss)
library(marginaleffects)

get_coef.gamlss <- function(model, ...){
  dots <- list(...)
  
  if (is.null(dots$what))
    stop("Argument `what` indicating the parameter of interest is missing.")
  
  out <- coef(model, what = dots$what)
  
  return(out)
}

set_coef.gamlss <- function(model, coefs, ...){
  dots <- list(...)
  
  if (is.null(dots$what))
    stop("Argument `what` indicating the parameter of interest is missing.")
  
  p <- paste0(dots$what, ".coefficients")
  model[[p]][names(coefs)] <- coefs
  out <- model
  
  return(out)
}

model <- gamlss(am ~ disp + hp, data = mtcars, family = "BI")
np <- length(get_coef.gamlss(model, what = "mu"))
model_new <- set_coef.gamlss(model, rep(0, np), what = "mu")
any(predict(model) != predict(model_new))
[1] FALSE
```

I contacted the author of the R-package `gamlss` to make refitting as an optional argument and he replied that he will look into it. In the meantime, I modified the method `gamlss::predict` and I incorporated it as a method for the package `marginaleffects`. I am not quite sure whether that is the best decision for the design of the package `marginaleffects` though. In addirion, the predictions used to calculate the standard errors are not "safe" as we set `refit = FALSE`. 

Ideally, the method predict should be provided by the original package to avoid future discrepancies. At least, I think this is a start to implement possible solutions. We could add warnings making the user aware of the issues.

Furthermore, the ellipsis is required as argument for the gamlss methods (`set_coef`, `get_coef`, `get_vcov` and `get_predict`) to indicate the parameter of interest (`what`). Consequently, I had to standardize including ellipsis as argument to all methods for other classes of objects.

# Libraries
```
library(gamlss)
library(marginaleffects) # devtools::install_github("dnzmarcio/marginaleffects")
```

# GLM: Binomial
```
data(mtcars, package = "datasets")

fit0 <- glm(am ~ disp + hp, data = mtcars, family = "binomial")
ref <- marginaleffects(fit0)
summary(ref)
# Average marginal effects 
# Term    Effect Std. Error z value  Pr(>|z|)     2.5 %    97.5 %
# 1 disp -0.008001   0.002440  -3.279 0.0010403 -0.012783 -0.003219
# 2   hp  0.010227   0.003957   2.585 0.0097478  0.002472  0.017982
# 
# Model type:  glm 
# Prediction type:  response 

fit1 <- gamlss(am ~ disp + hp, data = mtcars, family = "BI")
test <- marginaleffects(fit1, what = "mu")
summary(test)
# Average marginal effects 
# Term    Effect Std. Error z value   Pr(>|z|)     2.5 %    97.5 %
# 1 disp -0.008001   0.002387  -3.352 0.00080243 -0.012679 -0.003323
# 2   hp  0.010227   0.003887   2.631 0.00850566  0.002609  0.017844
# 
# Model type:  gamlss 
# Prediction type:  response 

## Results are not identical as the standard errors of GAMLSS R-package are different:

summary(fit0)
# Call:
#   glm(formula = am ~ disp + hp, family = "binomial", data = mtcars)
# 
# Deviance Residuals: 
#   Min       1Q   Median       3Q      Max  
# -1.9665  -0.3090  -0.0017   0.3934   1.3682  
# 
# Coefficients:
#   Estimate Std. Error z value Pr(>|z|)  
# (Intercept)  1.40342    1.36757   1.026   0.3048  
# disp        -0.09518    0.04800  -1.983   0.0474 *
#   hp           0.12170    0.06777   1.796   0.0725 .
# ---
#   Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# (Dispersion parameter for binomial family taken to be 1)
# 
# Null deviance: 43.230  on 31  degrees of freedom
# Residual deviance: 16.713  on 29  degrees of freedom
# AIC: 22.713
# 
# Number of Fisher Scoring iterations: 8

summary(fit1)
# ******************************************************************
#   Family:  c("BI", "Binomial") 
# 
# Call:  gamlss(formula = am ~ disp + hp, family = "BI", data = mtcars) 
# 
# Fitting method: RS() 
# 
# ------------------------------------------------------------------
#   Mu link function:  logit
# Mu Coefficients:
#   Estimate Std. Error t value Pr(>|t|)  
# (Intercept)  1.40342    1.36968   1.025   0.3140  
# disp        -0.09518    0.04638  -2.052   0.0493 *
#   hp           0.12170    0.06558   1.856   0.0737 .
# ---
#   Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# ------------------------------------------------------------------
#   No. of observations in the fit:  32 
# Degrees of Freedom for the fit:  3
# Residual Deg. of Freedom:  29 
# at cycle:  2 
# 
# Global Deviance:     16.71293 
# AIC:     22.71293 
# SBC:     27.11014 
# ******************************************************************
```
# Beta
```
library(betareg)
data("GasolineYield", package = "betareg")
attr(GasolineYield$batch, "contrasts") <- NULL

fit0 <- betareg(yield ~ batch + temp, data = GasolineYield)
ref <- marginaleffects(fit0)
summary(ref)

# Average marginal effects 
# Term Contrast    Effect Std. Error z value   Pr(>|z|)     2.5 %    97.5 %
# 1  batch    2 - 1 -0.076114  1.765e-02  -4.312 1.6166e-05 -0.110709 -0.041519
# 2  batch    3 - 1 -0.030388  1.806e-02  -1.682   0.092477 -0.065787  0.005012
# 3  batch    4 - 1 -0.119566  1.469e-02  -8.138 4.0104e-16 -0.148361 -0.090770
# 4  batch    5 - 1 -0.107842  1.528e-02  -7.057 1.6985e-12 -0.137793 -0.077892
# 5  batch    6 - 1 -0.122593  1.535e-02  -7.984 1.4153e-15 -0.152688 -0.092499
# 6  batch    7 - 1 -0.189694  1.401e-02 -13.535 < 2.22e-16 -0.217162 -0.162226
# 7  batch    8 - 1 -0.195172  1.414e-02 -13.798 < 2.22e-16 -0.222895 -0.167448
# 8  batch    9 - 1 -0.207161  1.467e-02 -14.120 < 2.22e-16 -0.235916 -0.178405
# 9  batch   10 - 1 -0.242614  1.305e-02 -18.597 < 2.22e-16 -0.268184 -0.217044
# 10  temp    dY/dX  0.001607  5.789e-05  27.753 < 2.22e-16  0.001493  0.001720
# 
# Model type:  betareg 
# Prediction type:  response

fit1 <- gamlss(yield ~ batch + temp, family = "BE",
               data = GasolineYield)
test <- marginaleffects(fit1, what = "mu")
summary(test)

# Average marginal effects 
# Term Contrast    Effect Std. Error z value   Pr(>|z|)     2.5 %    97.5 %
# 1  batch    2 - 1 -0.076115  1.787e-02  -4.259 2.0572e-05 -0.111146 -0.041084
# 2  batch    3 - 1 -0.030389  1.829e-02  -1.662   0.096551 -0.066230  0.005452
# 3  batch    4 - 1 -0.119567  1.491e-02  -8.019 1.0622e-15 -0.148789 -0.090345
# 4  batch    5 - 1 -0.107844  1.541e-02  -6.998 2.5898e-12 -0.138047 -0.077641
# 5  batch    6 - 1 -0.122594  1.555e-02  -7.885 3.1413e-15 -0.153067 -0.092122
# 6  batch    7 - 1 -0.189696  1.415e-02 -13.402 < 2.22e-16 -0.217438 -0.161954
# 7  batch    8 - 1 -0.195174  1.422e-02 -13.721 < 2.22e-16 -0.223054 -0.167294
# 8  batch    9 - 1 -0.207162  1.487e-02 -13.936 < 2.22e-16 -0.236297 -0.178026
# 9  batch   10 - 1 -0.242616  1.323e-02 -18.339 < 2.22e-16 -0.268544 -0.216687
# 10  temp    dY/dX  0.001607  5.769e-05  27.848 < 2.22e-16  0.001493  0.001720
# 
# Model type:  gamlss 
# Prediction type:  response 

## Results are not identical as the standard errors of GAMLSS R-package are different:

summary(fit0)
# Call:
#   betareg(formula = yield ~ batch + temp, data = GasolineYield)
# 
# Standardized weighted residuals 2:
#   Min      1Q  Median      3Q     Max 
# -2.8750 -0.8149  0.1601  0.8384  2.0483 
# 
# Coefficients (mean model with logit link):
#   Estimate Std. Error z value Pr(>|z|)    
# (Intercept) -4.4318422  0.1485493 -29.834  < 2e-16 ***
#   batch2      -0.4051320  0.0958164  -4.228 2.36e-05 ***
#   batch3      -0.1554190  0.0928092  -1.675    0.094 .  
# batch4      -0.6680148  0.0832382  -8.025 1.01e-15 ***
#   batch5      -0.5939771  0.0858653  -6.918 4.60e-12 ***
#   batch6      -0.6875671  0.0886422  -7.757 8.72e-15 ***
#   batch7      -1.1840366  0.0919797 -12.873  < 2e-16 ***
#   batch8      -1.2318282  0.0956153 -12.883  < 2e-16 ***
#   batch9      -1.3419359  0.1069140 -12.552  < 2e-16 ***
#   batch10     -1.7277289  0.1012294 -17.067  < 2e-16 ***
#   temp         0.0109669  0.0004126  26.577  < 2e-16 ***
#   
#   Phi coefficients (precision model with identity link):
#   Estimate Std. Error z value Pr(>|z|)    
# (phi)    440.3      110.0   4.002 6.29e-05 ***
#   ---
#   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
# 
# Type of estimator: ML (maximum likelihood)
# Log-likelihood:  84.8 on 12 Df
# Pseudo R-squared: 0.9617
# Number of iterations: 40 (BFGS) + 5 (Fisher scoring)

summary(fit1)
# ******************************************************************
#   Family:  c("BE", "Beta") 
# 
# Call:  gamlss(formula = yield ~ batch + temp, family = "BE",  
#               data = GasolineYield) 
# 
# Fitting method: RS() 
# 
# ------------------------------------------------------------------
#   Mu link function:  logit
# Mu Coefficients:
#   Estimate Std. Error t value Pr(>|t|)    
# (Intercept) -4.4318573  0.1493067 -29.683  < 2e-16 ***
#   batch2      -0.4051355  0.0968303  -4.184 0.000458 ***
#   batch3      -0.1554256  0.0938899  -1.655 0.113451    
# batch4      -0.6680208  0.0841878  -7.935 1.32e-07 ***
#   batch5      -0.5939862  0.0862197  -6.889 1.08e-06 ***
#   batch6      -0.6875737  0.0894373  -7.688 2.14e-07 ***
#   batch7      -1.1840533  0.0918073 -12.897 3.76e-11 ***
#   batch8      -1.2318442  0.0949321 -12.976 3.37e-11 ***
#   batch9      -1.3419427  0.1077308 -12.456 7.01e-11 ***
#   batch10     -1.7277380  0.1015299 -17.017 2.30e-13 ***
#   temp         0.0109669  0.0004081  26.872  < 2e-16 ***
#   ---
#   Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# ------------------------------------------------------------------
#   Sigma link function:  logit
# Sigma Coefficients:
#   Estimate Std. Error t value Pr(>|t|)    
# (Intercept)  -2.9961     0.1309  -22.89 8.09e-16 ***
#   ---
#   Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# ------------------------------------------------------------------
#   No. of observations in the fit:  32 
# Degrees of Freedom for the fit:  12
# Residual Deg. of Freedom:  20 
# at cycle:  5 
# 
# Global Deviance:     -169.5951 
# AIC:     -145.5951 
# SBC:     -128.0063 
# ******************************************************************
```

# Other classes

I did not test other classes of objects as I assume that adding ellipsis to their methods will not create any issues.

# Session Info

```
devtools::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.0 (2022-04-22 ucrt)
 os       Windows 10 x64 (build 19044)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       America/Los_Angeles
 date     2022-07-25
 rstudio  2022.02.3+492 Prairie Trillium (desktop)
 pandoc   NA

─ Packages ─────────────────────────────────────────────────────────────────────────
 package         * version    date (UTC) lib source
 backports         1.4.1      2021-12-13 [1] CRAN (R 4.2.0)
 betareg         * 3.1-4      2021-02-09 [1] CRAN (R 4.2.1)
 cachem            1.0.6      2021-08-19 [1] CRAN (R 4.2.1)
 callr             3.7.0      2021-04-20 [1] CRAN (R 4.2.0)
 checkmate         2.1.0      2022-04-21 [1] CRAN (R 4.2.0)
 cli               3.3.0      2022-04-25 [1] CRAN (R 4.2.0)
 crayon            1.5.1      2022-03-26 [1] CRAN (R 4.2.0)
 data.table        1.14.2     2021-09-27 [1] CRAN (R 4.2.0)
 devtools          2.4.3      2021-11-30 [1] CRAN (R 4.2.1)
 ellipsis          0.3.2      2021-04-29 [1] CRAN (R 4.2.0)
 fastmap           1.1.0      2021-01-25 [1] CRAN (R 4.2.0)
 flexmix           2.3-18     2022-06-07 [1] CRAN (R 4.2.1)
 Formula           1.2-4      2020-10-16 [1] CRAN (R 4.2.0)
 fs                1.5.2      2021-12-08 [1] CRAN (R 4.2.0)
 gamlss          * 5.4-3      2022-04-24 [1] CRAN (R 4.2.0)
 gamlss.data     * 6.0-2      2021-11-07 [1] CRAN (R 4.2.0)
 gamlss.dist     * 6.0-3      2022-03-08 [1] CRAN (R 4.2.0)
 generics          0.1.3      2022-07-05 [1] CRAN (R 4.2.0)
 glue              1.6.2      2022-02-24 [1] CRAN (R 4.2.0)
 insight           0.18.0     2022-07-05 [1] CRAN (R 4.2.1)
 lattice           0.20-45    2021-09-22 [2] CRAN (R 4.2.0)
 lifecycle         1.0.1      2021-09-24 [1] CRAN (R 4.2.0)
 lmtest            0.9-40     2022-03-21 [1] CRAN (R 4.2.1)
 magrittr          2.0.3      2022-03-30 [1] CRAN (R 4.2.0)
 marginaleffects * 0.6.0.9000 2022-07-25 [1] local
 MASS            * 7.3-56     2022-03-23 [2] CRAN (R 4.2.0)
 Matrix            1.4-1      2022-03-23 [2] CRAN (R 4.2.0)
 memoise           2.0.1      2021-11-26 [1] CRAN (R 4.2.1)
 modeltools        0.2-23     2020-03-05 [1] CRAN (R 4.2.0)
 nlme            * 3.1-157    2022-03-25 [2] CRAN (R 4.2.0)
 nnet              7.3-17     2022-01-16 [2] CRAN (R 4.2.0)
 pkgbuild          1.3.1      2021-12-20 [1] CRAN (R 4.2.1)
 pkgload           1.3.0      2022-06-27 [1] CRAN (R 4.2.1)
 prettyunits       1.1.1      2020-01-24 [1] CRAN (R 4.2.0)
 processx          3.5.3      2022-03-25 [1] CRAN (R 4.2.0)
 ps                1.7.0      2022-04-23 [1] CRAN (R 4.2.0)
 purrr             0.3.4      2020-04-17 [1] CRAN (R 4.2.0)
 R6                2.5.1      2021-08-19 [1] CRAN (R 4.2.0)
 remotes           2.4.2      2021-11-30 [1] CRAN (R 4.2.1)
 rlang             1.0.3      2022-06-27 [1] CRAN (R 4.2.1)
 rstudioapi        0.13       2020-11-12 [1] CRAN (R 4.2.0)
 sandwich          3.0-2      2022-06-15 [1] CRAN (R 4.2.1)
 sessioninfo       1.2.2      2021-12-06 [1] CRAN (R 4.2.1)
 survival          3.3-1      2022-03-03 [2] CRAN (R 4.2.0)
 usethis           2.1.6      2022-05-25 [1] CRAN (R 4.2.1)
 zoo               1.8-10     2022-04-15 [1] CRAN (R 4.2.1)
```

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
This looks fantastic! Thanks so much for taking the time @dnzmarcio !

A few quick questions:

1. Could you remove `predict.gamlss()` and fit all this code inside `get_predict()`? We don't actually need `predict()` because `marginaleffects` never calls that internally. And that way we don't export a method that will conflict with the `gamlss` namespace.
2. Is it possible to write a few very simple test? Maybe comparing to `betareg` as in your examples, or ideally to some external benchmark? Even if those are super minmalist, I've found it useful to have a few smoketests. See `inst/tinytest` for examples.
3. I understand the root of the problem for standard errors, but why do we see standard errors in the output of your code above? If we can't yet compute standard errors for this kind of model, I think a good strategy would be to write a `get_vcov.gamlss()` method that always returns `NULL`, and also includes some code comments to explain why we don't want to return uncertainty estimates.

Thanks again!

**Comment by vincentarelbundock** [comment]
Oh sorry. Your new `predict.gamlss()` method handles the standard error issue. Great!

**Comment by dnzmarcio** [comment]
Thanks for the great R-package. Addressing your question:

1. Good catch! That's a great idea.
2. I will follow the one provided for `betareg`. I know that `emmeans` provides support to `gamlss` when there is no smoothing term. 
3. You are correct. The new predict handles the standard error.

**Comment by vincentarelbundock** [comment]
Great! 

Optional, but feel to add an item to the NEWS and your name as a contributor in DESCRIPTION. Here's an example from a different repo: https://github.com/vincentarelbundock/modelsummary/blob/main/DESCRIPTION

**Comment by dnzmarcio** [comment]
I was finally able to finish adding tests and I also added myself as contributor. I was unsure about the NEWS.md though.

**Comment by vincentarelbundock** [comment]
Sounds great! Thanks so much for taking the time!

I'm working on some other `marginaleffects` stuff right now, so I'll probably be able to take a look and merge it very soon. Will let you know when it's available in the main branch on Github. In any case, this will certainly be part of the next release on CRAN (2-3 weeks).

**Comment by vincentarelbundock** [comment]
This is now merged and available in the dev version on Github.

Thanks again for all the work you put into this. I really appreciate it!

**Pull request merged**
