### PR TITLE
Benchmark: DO NOT MERGE

### PR DESCRIPTION
**Pull request by vincentarelbundock**
@etiennebacher I added an artificial 2 second sleep time to the `slopes()` function.

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
@etiennebacher this is super cool! Really amazing!

**Comment by etiennebacher** [comment]
Nice! Let's keep this PR open as an experiment and I'll do more tweaks in followup PRs

**Comment by vincentarelbundock** [comment]
@etiennebacher any ideas how we can trigger the github action again? I tried to push a new commit with a single character change but it didn't run the benchmark again.

**Comment by etiennebacher** [comment]
It updated the original github actions comment, you can see it now contains the table with all the new benchmarks. I did this to avoid having one new comment every time the actions run.

**Comment by vincentarelbundock** [comment]
ah yeah, that's much better, thanks

**Pull request closed without merging**
