### PR TITLE
related to #810 and #828

### PR DESCRIPTION
**Pull request by strengejacke**
@vincentarelbundock I will also add tests later. Feel free to modify or suggest other wording for the error message. I think error is OK because I'm not sure the warning is recognized in 100% of all use cases. But we may switch to a warning, too, however, now that we have the possibility to avoid this error, an error is also ok.

### CODE REVIEW

**Comment by strengejacke** [comment]
I'm not familiar with your CI/test-setup, but it _seems_ like the current errors are unrelated to my commit.

**Comment by vincentarelbundock** [comment]
Thanks, this looks great!

I’m being picky now, but I feel the language might be a bit too accusatory. Frankly, I’m not sure I understand the source of the problem, so maybe best to just link to the issue on the glmmTMB GitHub?

sorry to ask for changes!

**Comment by strengejacke** [comment]
Yes, no problem! I'll revise the wording (though, as Northern German, everything we say sounds accusatory, even compliments, so I may need some tries for the final wording :-)).

**Comment by vincentarelbundock** [comment]
awesome, thanks!

**Pull request merged**
