### PR TITLE
Added support for svyolr and multiple hypothesis strings

### PR DESCRIPTION
**Pull request by ngreifer**
No new tests. `svyolr` objects work just like `polr` objects. `hypothesis` can now accept multipel strings, e.g., `c("b1 = b2", "b3 = b4")`. This was already enabled except that checks checked for a string instead of a character vector. All elemtns must have `=`, i.e., `c("b1 = b2", "pairwise")` is not allowed and will be correctly flagged.

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Nice, thanks! Maybe needs a document() call to buikd and test?

**Comment by ngreifer** [comment]
Fixed!

**Comment by vincentarelbundock** [comment]
Thanks for the great contribution! Merged.

**Comment by ngreifer** [comment]
I need to justify my authorship on the paper somehow! 😝

**Pull request merged**
